- type: listing
  id: VendorVehicleSecway
  productEntity: VehicleSecwayFilled
  cost:
    NTCredit: 1000
  categories:
  - SLSecurity
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 2
  - !type:BuyerAccessCondition

- type: listing
  id: VendorBrutepackBlueSec
  productEntity: BrutepackBlue
  cost:
    NTCredit: 34
  categories:
  - SLBrigmedic
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 4
  - !type:BuyerAccessCondition
    access: Brigmedic

- type: listing
  id: VendorBlueOintmentSec
  icon: { sprite: /Textures/_FarHorizons/Objects/Specific/Medical/blue_ointment.rsi, state: icon }
  productEntity: BlueOintment
  cost:
    NTCredit: 34
  categories:
  - SLBrigmedic
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 4
  - !type:BuyerAccessCondition
    access: Brigmedic

- type: listing
  id: VendorBrutepackRedSec
  productEntity: BrutepackRed
  cost:
    NTCredit: 68
  categories:
  - SLBrigmedic
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 4
  - !type:BuyerAccessCondition
    access: Brigmedic

- type: listing
  id: VendorBrutepackBlackSec
  productEntity: BrutepackBlack
  cost:
    NTCredit: 68
  categories:
  - SLBrigmedic
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 4
  - !type:BuyerAccessCondition
    access: Brigmedic

- type: listing
  id: VendorBrutepackBeigeSec
  productEntity: BrutepackBeige
  cost:
    NTCredit: 68
  categories:
  - SLBrigmedic
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 4
  - !type:BuyerAccessCondition
    access: Brigmedic



#region NeoSol


# SecDrobe

- type: vendingMachineInventory
  id: SecDrobeInventoryNeoSol
  startingInventory:
    ClothingBackpackSyndicateSecurity: 3
    ClothingBackpackSatchelSyndicateSecurity: 3
    ClothingBackpackDuffelSyndicateSecurity: 3
    ClothingUniformJumpsuitSecSyndi: 3
    ClothingShoesBootsJackSyndi: 3
    ClothingHeadHatBeretSecuritySyndi: 3
    ClothingHeadHatSecurityCapSyndi: 3
    ClothingHeadBandRed: 3
    ClothingMaskNeckGaiterRed: 3
    ClothingHandsGlovesSecurityRed: 3
    ClothingHandsGlovesSecurityFingerlessRed: 3
    ClothingUniformJumpskirtSecSyndi: 3
    ClothingUniformJumpsuitSecGreySyndi: 3
    ClothingUniformJumpskirtSecGreySyndi: 3
    #ClothingUniformJumpsuitSecBlue: 3
    #ClothingUniformSecurityTshirt: 3
    ClothingHeadsetSecuritySyndi: 3
    #ClothingOuterWinterSec: 2
    ClothingOuterArmorBasicSyndi: 2
    ClothingOuterArmorBasicSlimSyndi: 2
    ClothingOuterArmorPlateSyndi: 2
    ClothingOuterArmorStabSyndi: 2
    ClothingOuterArmorHeatAbsorbSyndi: 2
    ClothingHeadHelmetPlateSyndi: 2
    ClothingHeadHelmetStabproofSyndi: 2
    ClothingHeadHelmetHeatAbsorbentSyndi: 2
    ClothingNeckScarfStripedRed: 3
    ClothingEyesBlindfold: 1
    ClothingShoesBootsJackSyndi: 1
    #ClothingShoesBootsWinterSec: 2
    ClothingOuterSecurityBomberSyndi: 2
    ClothingOuterWindbreakerSecuritySyndi: 2
    ClothingHeadHelmetJustice: 1
  contrabandInventory:
    ClothingMaskClownSecurity: 1
    ClothingMaskMimeSecurity: 1
    ToyFigurineSecurity: 1
    ToyFigurineWarden: 1
    ToyFigurineHeadOfSecurity: 1