using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared._FarHorizons.Vehicles.Equipment;
using Robust.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Vehicles.Components;
using Robust.Client.AutoGenerated;
using Content.Client._Starlight.UI;
using Content.Shared.Damage.Components;

namespace Content.Client._FarHorizons.Vehicles.Equipment;

[GenerateTypedNameReferences]
public sealed partial class VehicleEquipmentMenu : FancyWindow
{
    public event Action<NetEntity, EquipmentType>? OnUninstallButtonPressed;
    private Dictionary<EquipmentType, EntityUid?> _cachedEquipment = new();
    private readonly Dictionary<EquipmentType, int> _cachedIntegrity = new();
    private readonly IEntityManager _entityManager;
    public VehicleEquipmentMenu()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
    }

    public void UpdateState(VehicleEquipmentUiState state)
    {
        var target = _entityManager.GetEntity(state.Vehicle);
        if (target == null 
        || !_entityManager.TryGetComponent<VehicleModsComponent>(target, out var vmComp)
        || !_entityManager.TryGetComponent<VehicleComponent>(target, out var vehicle)
        || !_entityManager.TryGetComponent<MetaDataComponent>(target, out var metaData)) 
            return;
        
        NameLabel.Text = metaData.EntityName;
        SpriteView.SetEntity(target.Value);
        SpriteView.Visible = true;

        HealthPercent.Text = $"{state.Integrity}%";
        HealthBar.Value = state.Integrity;

        FuelLabel.Text = vehicle.CellPowered == true ? "Power" : "Fuel"; 
        FuelPercent.Text = $"{state.Power}%";
        FuelBar.Value = state.Power;
        
        if (!EquipmentChanged(vmComp.Equipment) && !IntegrityChanged(vmComp.Equipment))
            return;

        _cachedEquipment = new Dictionary<EquipmentType, EntityUid?>(vmComp.Equipment);

        EquipmentPanel.DisposeAllChildren();
        _cachedIntegrity.Clear();

        foreach (var (type, mod) in vmComp.Equipment)
        {
            var column = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(0, 10, 0, 0)
            };

            var modsButton = new Button
            {
                HorizontalAlignment = HAlignment.Center,
                SetWidth = 300,
                Disabled = true,
            };

            var modsButtonText = new RichTextLabel
            {
                Text = type.ToString(),
                HorizontalAlignment = HAlignment.Left,
                Margin = new Thickness(10, 0, 0, 0)
            };

            modsButton.AddChild(modsButtonText);

            column.AddChild(modsButton);
            
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(50, 5, 0, 0)
            };

            var equipmentButton = new Button
            {
                SetWidth = mod != null ? 135 : 275,
                HorizontalAlignment = HAlignment.Right,
                Disabled = true
            };
            
            var equipText = "Empty";
            int integrity = 0;
            if(mod != null && _entityManager.TryGetComponent<DamageableComponent>(mod, out var damageComp) 
                && _entityManager.TryGetComponent<VehicleEquipmentComponent>(mod, out var veComp))
            {
                integrity = (int)((veComp.Health - damageComp.TotalDamage) * 100 / veComp.Health);
                _cachedIntegrity[type] = integrity;
                equipText = $"{_entityManager.GetComponent<MetaDataComponent>(mod.Value).EntityName}: {integrity}%";
            }

            var equipmentButtonText = new RichTextLabel
            {
                Text = equipText,
                HorizontalAlignment = HAlignment.Left
            };

            equipmentButton.AddChild(equipmentButtonText);

            if(mod != null)
            {
                var installationButton = new Button
                {
                    SetWidth = 135,
                    SetHeight = 30,
                    HorizontalAlignment = HAlignment.Right,
                    Margin = new Thickness(5, 0, 0, 0) 
                };

                var installationButtonText = new RichTextLabel
                {
                    Text = "Uninstall",
                    HorizontalAlignment = HAlignment.Left
                };
                installationButton.OnPressed += _ => OnUninstallButtonPressed?.Invoke(_entityManager.GetNetEntity(mod.Value), type);
                installationButton.AddChild(installationButtonText);
            
                row.AddChildren([equipmentButton, installationButton]);   
            }
            else
                row.AddChild(equipmentButton);

            column.AddChild(row);
            EquipmentPanel.AddChild(column);
        }
    }

    private bool EquipmentChanged(Dictionary<EquipmentType, EntityUid?> current)
    {
        if (_cachedEquipment.Count != current.Count)
            return true;

        foreach (var (key, value) in current)
        {
            if (!_cachedEquipment.TryGetValue(key, out var cachedValue))
                return true;

            if (cachedValue != value)
                return true;
        }

        return false;
    }

    private bool IntegrityChanged(Dictionary<EquipmentType, EntityUid?> equipment)
    {
        foreach (var (type, mod) in equipment)
        {
            int integrity = 0;

            if (mod != null &&
                _entityManager.TryGetComponent<DamageableComponent>(mod, out var damageComp) &&
                _entityManager.TryGetComponent<VehicleEquipmentComponent>(mod, out var veComp))
            {
                integrity = (int)((veComp.Health - damageComp.TotalDamage) * 100 / veComp.Health);
            }

            if (!_cachedIntegrity.TryGetValue(type, out var cached) || cached != integrity)
                return true;
        }

        return false;
    }
}