using System.Linq;
using Content.Client.Mind;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCOperations.Systems;
using Content.Shared.Humanoid;
using Content.Shared.Mind;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Content.Shared.Roles.Jobs;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Network;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization;
using Robust.Shared.Utility;

namespace Content.Client._FarHorizons.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class OperationsUiFragment : BoxContainer
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly SpriteSystem _spriteSystem;

    private string? _selectedTargetName;
    private List<CCOperativeAgent> _agents = new();
    private List<CCOperativeAgentUiItem> _agentsData = new();

    public OperationsUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();

        SearchBar.OnTextChanged += OnSearchBarTextChanged;
    }

    private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
    {
        if (!String.IsNullOrWhiteSpace(args.Text))
        {
            List<CCOperativeAgent> found = new();
            foreach (CCOperativeAgentUiItem agent in _agentsData)
            {
                if (
                    agent.Name.Contains(args.Text) || 
                    agent.JobTitle.Contains(args.Text, StringComparison.OrdinalIgnoreCase)
                )
                    found.Add(new CCOperativeAgent(agent.Id));
            }
            UpdateState(found, false);
        }
        else
            UpdateState(_agents, false);
    }

    public void UpdateState(List<CCOperativeAgent> records, bool refresh = true)
    {
        if (records.Count == 0)
        {
            NoRecords.Visible = true;
            RecordsList.Visible = false;
            RecordUnselected.Visible = false;
            PersonContainer.Visible = false;

            _selectedTargetName = null;
            if (refresh)
            {
                _agents.Clear();
                _agentsData.Clear();
            }

            RecordsList.PopulateList(new List<ListData>());

            return;
        }

        NoRecords.Visible = false;
        RecordsList.Visible = true;
        RecordUnselected.Visible = true;
        PersonContainer.Visible = false;

        RecordsList.GenerateItem = GenerateItem;
        RecordsList.ItemPressed = OnItemSelected;

        if (refresh)
        {
            _agents = records;
            var newAgentsData = new List<CCOperativeAgentUiItem>();
            foreach (var agent in _agents)
            {
                var uid = new EntityUid(agent.Id);
                var entity = _entityManager.GetEntity(new NetEntity(agent.Id)); // MobStateComponent(CurrentState)
                
                var age = 0;
                var gender = "unknown";
                var species = "unknown";
                var name = "unknown";
                var state = "unknown";
                var job = "unknown";

                if (_entityManager.TryGetComponent<MobStateComponent>(uid, out var stateComponent))
                {
                    switch (stateComponent.CurrentState)
                    {
                        case MobState.Alive:
                            state = "Alive";
                            break;
                        case MobState.Dead:
                            state = "Dead";
                            break;
                    }
                }
                var mind = _entityManager.System<SharedMindSystem>().GetMind(entity);
                if (_entityManager.System<SharedJobSystem>().MindTryGetJobName(mind, out var jobName))
                    job = jobName;
                if (_entityManager.TryGetComponent<HumanoidAppearanceComponent>(uid, out var appearance))
                {
                    age = appearance.Age;
                    gender = appearance.Gender.ToString();
                    species = appearance.Species;
                }
                if (_entityManager.TryGetComponent<MindComponent>(uid, out var mindComponent))
                {
                    if (mindComponent.CharacterName != null)
                        name = mindComponent.CharacterName;
                }
                newAgentsData.Add(
                    new CCOperativeAgentUiItem(agent.Id, false, name, age, job, species, gender, state)
                );
            }
        }
        var dataList = _agentsData.Select(r => new AgentListData(r)).ToList();
        RecordsList.PopulateList(dataList);
    }

    private void OnItemSelected(BaseButton.ButtonEventArgs args, ListData data)
    {
        if (data is not AgentListData(var record))
            return;

        FormattedMessage GetLoc(string fluentId, params (string,object)[] args)
        {
            var msg = new FormattedMessage();
            var fluent = Loc.GetString(fluentId, args);
            msg.AddMarkupPermissive(fluent);
            return msg;
        }

        // Set personal info
        PersonName.Text = record.Name;
        TargetAge.SetMessage(GetLoc(
            "cc-operations-age-label",
            ("age", record.Age)
        ));
        TargetJob.SetMessage(GetLoc(
            "cc-operations-job-label",
            ("job", record.JobTitle.ToLower())
        ));
        TargetSpecies.SetMessage(GetLoc(
            "cc-operations-species-label",
            ("species", record.Species.ToLower())
        ));
        TargetGender.SetMessage(GetLoc(
            "cc-operations-gender-label",
            ("gender", record.Gender)
        ));

        RecordUnselected.Visible = false;
        PersonContainer.Visible = true;

        // Save selected item
        _selectedTargetName = record.Name;
    }

    private void GenerateItem(ListData data, ListContainerButton button)
    {
        if (data is not AgentListData(var record))
            return;

        var box = new BoxContainer() { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true };
        var label = new Label() { Text = record.Name };
        var rect = new TextureRect()
        {
            TextureScale = new(2.2f),
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Center,
            Margin = new(0f, 0f, 6f, 0f),
        };
        //
        // if (_prototypeManager.TryIndex<SecurityIconPrototype>(record.TargetInfo.JobIcon, out var prototype))
        // {
        //     rect.Texture = _spriteSystem.Frame0(prototype.Icon);
        // }

        box.AddChild(rect);
        box.AddChild(label);
        button.AddChild(box);
        button.AddStyleClass(ListContainer.StyleClassListContainerButton);

        if (record.Name.Equals(_selectedTargetName))
        {
            button.Pressed = true;
            // For some reason the event is not called when `Pressed` changed, call it manually.
            OnItemSelected(
                new(button, new(new(), BoundKeyState.Down, new(), false, new(), new())),
                data);
        }
    }
}

internal record AgentListData(CCOperativeAgentUiItem Record) : ListData;
