using System.Linq;
using Content.Client._FarHorizons.CCOperations;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCOperations.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._FarHorizons.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class OperationsUiFragment : BoxContainer
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly CCOperationsSystem _operations;

    private string? _selectedTargetName;
    private int? _selectedTargetId;
    private List<CCOperativeAgent> _agents = new();

    public OperationsUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBar.OnTextChanged += OnSearchBarTextChanged;
        _operations = _entityManager.System<CCOperationsSystem>();
    }

    private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
    {
        if (!String.IsNullOrWhiteSpace(args.Text))
        {
            List<CCOperativeAgent> found = new();
            foreach (CCOperativeAgent agent in _agents)
            {
                if (
                    agent.Name.Contains(args.Text) || 
                    agent.JobTitle.Contains(args.Text, StringComparison.OrdinalIgnoreCase)
                )
                    found.Add(agent);
            }
            UpdateState(found, false);
        }
        else
            UpdateState(_agents, false);
    }

    public void UpdateState(List<CCOperativeAgent> records, bool refresh = true)
    {
        if (records.Count == 0)
        {
            NoRecords.Visible = true;
            RecordsList.Visible = false;
            RecordUnselected.Visible = false;
            PersonContainer.Visible = false;

            _selectedTargetName = null;
            if (refresh)
            {
                _agents.Clear();
            }

            RecordsList.PopulateList(new List<ListData>());

            return;
        }

        NoRecords.Visible = false;
        RecordsList.Visible = true;
        RecordUnselected.Visible = true;
        PersonContainer.Visible = false;

        RecordsList.GenerateItem = GenerateItem;
        RecordsList.ItemPressed = OnItemSelected;

        if (refresh)
        {
            _agents = records;
        }
        var dataList = _agents.Select(r => new AgentListData(r)).ToList();
        RecordsList.PopulateList(dataList);
    }

    private FormattedMessage GetLoc(string fluentId, params (string,object)[] args)
    {
        var msg = new FormattedMessage();
        var fluent = Loc.GetString(fluentId, args);
        msg.AddMarkupPermissive(fluent);
        return msg;
    }
    
    private void OnItemSelected(BaseButton.ButtonEventArgs args, ListData data)
    {
        if (data is not AgentListData(var record))
            return;

        // Set personal info
        PersonName.Text = record.Name;
        TargetAge.SetMessage(GetLoc(
            "cc-operations-age-label",
            ("age", record.Age)
        ));
        TargetJob.SetMessage(GetLoc(
            "cc-operations-job-label",
            ("job", record.JobTitle.ToLower())
        ));
        TargetSpecies.SetMessage(GetLoc(
            "cc-operations-species-label",
            ("species", record.Species.ToLower())
        ));
        TargetGender.SetMessage(GetLoc(
            "cc-operations-gender-label",
            ("gender", record.Gender)
        ));
        UplinkStatus.SetMessage(GetLoc(
            "cc-operations-uplink-label",
            ("status", record.UplinkOpen.ToString())
        ));
        UplinkToggleButton.OnPressed += OnUplinkToggled;
        NeutralizeButton.OnPressed += OnAgentNeutralizeActivated;

        RecordUnselected.Visible = false;
        PersonContainer.Visible = true;

        // Save selected item
        _selectedTargetName = record.Name;
        _selectedTargetId = record.Id;
    }

    private void OnUplinkToggled(BaseButton.ButtonEventArgs args)
    {
        UplinkToggleButton.Disabled = true;
        Timer.Spawn(1000, () => UplinkToggleButton.Disabled = false);

        var record = _agents.FirstOrNull(r => r.Id == _selectedTargetId);
        if (record is null) return;
        var newValue = !record.Value.UplinkOpen;
        _operations.ToggleAgentUplink(record.Value.Id, newValue);
        UplinkStatus.SetMessage(GetLoc(
            "cc-operations-uplink-label",
            ("status", newValue.ToString())
        ));
    }

    private void OnAgentNeutralizeActivated(BaseButton.ButtonEventArgs args)
    {
        var record = _agents.FirstOrNull(r => r.Id == _selectedTargetId);
        if (record is null) return;
        _operations.NeutralizeAgent(record.Value.Id);
    }

    private void GenerateItem(ListData data, ListContainerButton button)
    {
        if (data is not AgentListData(var record))
            return;

        var box = new BoxContainer() { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true };
        var label = new Label() { Text = record.Name };
        var rect = new TextureRect()
        {
            TextureScale = new(2.2f),
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Center,
            Margin = new(0f, 0f, 6f, 0f),
        };
        //
        // if (_prototypeManager.TryIndex<SecurityIconPrototype>(record.TargetInfo.JobIcon, out var prototype))
        // {
        //     rect.Texture = _spriteSystem.Frame0(prototype.Icon);
        // }

        box.AddChild(rect);
        box.AddChild(label);
        button.AddChild(box);
        button.AddStyleClass(ListContainer.StyleClassListContainerButton);

        if (record.Name.Equals(_selectedTargetName))
        {
            button.Pressed = true;
            // For some reason the event is not called when `Pressed` changed, call it manually.
            OnItemSelected(
                new(button, new(new(), BoundKeyState.Down, new(), false, new(), new())),
                data);
        }
    }
}

internal record AgentListData(CCOperativeAgent Record) : ListData;
