using System.Linq;
using Content.Client.CartridgeLoader.Cartridges;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCOperations.Systems;
using Content.Shared.CriminalRecords.Systems;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._FarHorizons.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class OperationsUiFragment : BoxContainer
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    private readonly SpriteSystem _spriteSystem;

    private string? _selectedTargetName;
    private List<CCOperativeAgent> _agents = new();

    public OperationsUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();

        SearchBar.OnTextChanged += OnSearchBarTextChanged;
    }

    private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
    {
        var found = !String.IsNullOrWhiteSpace(args.Text)
            ? _agents.FindAll(r =>
                r.TargetInfo.Name.Contains(args.Text) ||
                r.TargetInfo.JobTitle.ToString().Contains(args.Text, StringComparison.OrdinalIgnoreCase))
            : _agents;

        UpdateState(found, false);
    }

    public void UpdateState(List<CCOperativeAgent> records, bool refresh = true)
    {
        if (records.Count == 0)
        {
            NoRecords.Visible = true;
            RecordsList.Visible = false;
            RecordUnselected.Visible = false;
            PersonContainer.Visible = false;

            _selectedTargetName = null;
            if (refresh)
                _agents.Clear();

            RecordsList.PopulateList(new List<ListData>());

            return;
        }

        NoRecords.Visible = false;
        RecordsList.Visible = true;
        RecordUnselected.Visible = true;
        PersonContainer.Visible = false;

        RecordsList.GenerateItem = GenerateItem;
        RecordsList.ItemPressed = OnItemSelected;

        if (refresh)
            _agents = records;
    }

    private void OnItemSelected(BaseButton.ButtonEventArgs args, ListData data)
    {
        if (data is not AgentListData(var record))
            return;

        FormattedMessage GetLoc(string fluentId, params (string,object)[] args)
        {
            var msg = new FormattedMessage();
            var fluent = Loc.GetString(fluentId, args);
            msg.AddMarkupPermissive(fluent);
            return msg;
        }

        // Set personal info
        PersonName.Text = record.TargetInfo.Name;
        TargetAge.SetMessage(GetLoc(
            "cc-operations-age-label",
            ("age", record.TargetInfo.Age)
        ));
        TargetJob.SetMessage(GetLoc(
            "cc-operations-job-label",
            ("job", record.TargetInfo.JobTitle.ToLower())
        ));
        TargetSpecies.SetMessage(GetLoc(
            "cc-operations-species-label",
            ("species", record.TargetInfo.Species.ToLower())
        ));
        TargetGender.SetMessage(GetLoc(
            "cc-operations-gender-label",
            ("gender", record.TargetInfo.Gender)
        ));

        RecordUnselected.Visible = false;
        PersonContainer.Visible = true;

        // Save selected item
        _selectedTargetName = record.TargetInfo.Name;
    }

    private void GenerateItem(ListData data, ListContainerButton button)
    {
        if (data is not StatusListData(var record))
            return;

        var box = new BoxContainer() { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true };
        var label = new Label() { Text = record.TargetInfo.Name };
        var rect = new TextureRect()
        {
            TextureScale = new(2.2f),
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Center,
            Margin = new(0f, 0f, 6f, 0f),
        };

        if (_prototypeManager.TryIndex<SecurityIconPrototype>(record.TargetInfo.JobIcon, out var prototype))
        {
            rect.Texture = _spriteSystem.Frame0(prototype.Icon);
        }

        box.AddChild(rect);
        box.AddChild(label);
        button.AddChild(box);
        button.AddStyleClass(ListContainer.StyleClassListContainerButton);

        if (record.TargetInfo.Name.Equals(_selectedTargetName))
        {
            button.Pressed = true;
            // For some reason the event is not called when `Pressed` changed, call it manually.
            OnItemSelected(
                new(button, new(new(), BoundKeyState.Down, new(), false, new(), new())),
                data);
        }
    }
}

internal record AgentListData(CCOperativeAgent Record) : ListData;
