using System.Numerics;
using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Shuttles;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Map;

namespace Content.Client._FarHorizons.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class TurretControlConsoleWindow : FancyWindow, IComputerWindow<NavInterfaceState>
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly SharedTransformSystem _transformSystem;

    public event Action<Vector2?>? TargetSelected;
    public event Action? FireButtonPressed;

    public TurretControlConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _transformSystem = _entityManager.System<SharedTransformSystem>();

        RadarScreen.OnRadarClick += OnTargetClick;
        FireCannons.OnPressed += _ => FireButtonPressed?.Invoke();
        ResetTarget.OnPressed += _ => OnTargetClick(null);

        FireCannons.StyleBoxOverride = new StyleBoxFlat(Color.Red);
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Function != EngineKeyFunctions.UIRightClick)
            return;

        OnTargetClick(null);
    }

    public void UpdateState(NavInterfaceState scc) => RadarScreen.UpdateState(scc);

    private void OnTargetClick(EntityCoordinates coord) => OnTargetClick(_transformSystem.ToWorldPosition(coord));

    private void OnTargetClick(Vector2? coord) => TargetSelected?.Invoke(coord);

    public void RescuePing(SpaceRescuePingMessage ping) => RadarScreen.RescuePing(ping);

    
}
