using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Medical.Disease.Systems;
using Content.Shared.Chemistry.EntitySystems;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Containers;
using Robust.Shared.Timing;

namespace Content.Client._FarHorizons.Medical.Disease.UI;

[GenerateTypedNameReferences]
public sealed partial class VaccinatorMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly SharedContainerSystem _container;
    private readonly SharedSolutionContainerSystem _solutionContainer;
    private Dictionary<DiseaseData, float> _immunity = [];
    public EntityUid Entity;
    public VaccinatorMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _container = _entityManager.System<SharedContainerSystem>();
        _solutionContainer = _entityManager.System<SharedSolutionContainerSystem>();
    }

    public void SetEntity(EntityUid uid)
    {
        Entity = uid;
        MaterialsList.SetOwner(Entity);
        UpdateWindow();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateWindow();
    }

    public void UpdateWindow()
    {
        if(!_container.TryGetContainer(Entity, "sample", out var sampleContainer))
            return;
            
        var vial = sampleContainer.ContainedEntities.FirstOrDefault();
        if (vial == default)
            return;

        Dictionary<DiseaseData, float> newImmunity = [];
        if(!_solutionContainer.TryGetSolution(vial, "drink", out var solution))
            return;

        var immunities = solution.Value.Comp.Solution;
        foreach(var immunity in immunities)
        {
            if(immunity.Reagent.Data == null)
                continue;

            var diseaseData = immunity.Reagent.Data.OfType<DiseaseReagentData>().FirstOrDefault();
            if (diseaseData == null)
                continue;

            foreach (var (disease, value) in diseaseData.Immunity)
            {
                if (!newImmunity.TryGetValue(disease, out var existing) || value > existing)
                    newImmunity[disease] = value;
            }
        }

        if(newImmunity == _immunity)
            return;

        _immunity = newImmunity;

        ImmunityPanel.DisposeAllChildren();
        foreach(var immunity in _immunity)
        {
            var test = new Label()
            {
                Text = Loc.GetString(immunity.Key.Name)
            };
            ImmunityPanel.AddChild(test);
        }
    }
}