- type: antag
  id: ScientistAbductorAntag #FH
  name: abductors-ghost-role-name
  antagonist: true
  objective: roles-antag-abductor-objective
  requirements:
  - !type:RoleTimeRequirement
    role: JobSurgeon
    time: 3600 # 1 hour - Far Horizons // #Starlight - 3h
  playTimeTracker: AntagLoneAbductor

#FarHorizons Start
- type: antag
  id: AgentAbductorAntag
  name: abductora-ghost-role-name
  antagonist: true
  objective: roles-antag-abductor-objective
  requirements:
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer
    time: 3600 
  playTimeTracker: AntagLoneAbductor
#FarHorizons End