using System.Diagnostics.CodeAnalysis;
using Content.Client.UserInterface;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Fusion;
using Content.Shared._FarHorizons.Power.Generation.FusionGenerator;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._FarHorizons.Power.UI.FusionReactor;

[GenerateTypedNameReferences]
public sealed partial class FusionReactorControllerWindow : FancyWindow
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private readonly IGameTiming _gameTiming = default!;

    public Action<KeyValuePair<FusionAtom, FusionReactorTransferData>>? OnTransferSet;
    public Action<FusionReactorControllerSetExtractMessage>? OnExtractSet;
    public Action<float>? OnPressureSet;
    public Action<FusionReactorControllerSetMaserInjectMessage>? OnMaserSetInject;
    public Action<FusionReactorControllerEditInjectMessage>? OnEditInject;
    public Action? EjectPressed;

    private readonly Dictionary<NetEntity, BatteryStateEntry> _batteryEntries = [];
    private readonly Dictionary<NetEntity, MaserStateEntry> _maserEntries = [];
    private float _accumulator = 0f;
    private TimeSpan _timeSpan;

    // 28 gets us all the way to Nickel, which is as high as the reactor goes by default
    private const int NumberAtoms = 28;

    public FusionReactorControllerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Thank you IPCs for the neat font
        var consoleResource = _resourceCache.GetResource<FontResource>("/Fonts/_FarHorizons/VT323/vt323-latin-400-normal.ttf");
        var dataFont = new VectorFont(consoleResource, 15);

        foreach (var child in Overview.Children)
        {
            if (child is not Label label)
                continue;
            label.FontOverride = dataFont;
        }

        CenterCountdown.FontOverride = new VectorFont(consoleResource, 50);
        EjectButton.Label.FontOverride = new VectorFont(consoleResource, 20);
        EjectButton.ModulateSelfOverride = Color.FromHex("#FF0000");

        EditInjectOption.Clear();
        for (var p = 1; p <= NumberAtoms; p++)
        {
            EditInjectOption.AddItem(Loc.GetString($"periodic-table-element-{p}"), p);
        }

        ExtractionOption.Clear();
        foreach (var type in Enum.GetValues<FusionReactorPowerExtractType>())
        {
            ExtractionOption.AddItem(Loc.GetString($"fusion-reactor-controller-ui-{type.ToString().ToLower()}"), (int)type);
        }

        LeftTabWing.SetTabTitle(0, Loc.GetString("fusion-reactor-controller-ui-tab-contents"));
        LeftTabWing.SetTabTitle(1, Loc.GetString("fusion-reactor-controller-ui-tab-injection"));

        SortAtomList.OnPressed += _ => AtomList.Order();
        AtomList.DisplayUnit = Loc.GetString("fusion-reactor-controller-ui-unit-mol");

        SortInjectList.OnPressed += _ => InjectionList.Order();
        InjectionList.DisplayUnit = Loc.GetString("fusion-reactor-controller-ui-unit-mol");
        InjectionList.OnTransferSet += val => OnTransferSet?.Invoke(val);

        EditInjectToggle.OnPressed += _ => EditInjectBox.Visible = EditInjectToggle.Pressed;
        EditInjectOption.OnItemSelected += obj =>
        {
            EditInjectOption.SelectId(obj.Id);
            UpdateEditInjectButton();
        };
        EditInjectNumber.OnTextChanged += _ => UpdateEditInjectButton();
        EditInjectButton.OnPressed += _ => OnEditInjectAtom();

        RightTabWing.SetTabTitle(0, Loc.GetString("fusion-reactor-controller-ui-tab-powercontrol"));
        RightTabWing.SetTabTitle(1, Loc.GetString("fusion-reactor-controller-ui-tab-masercontrol"));

        ExtractionOption.OnItemSelected += obj =>
        {
            ExtractionOption.SelectId(obj.Id);
            SetExtractionButton.Disabled = false;
        };
        TemperatureSetting.OnTextChanged += _ => SetExtractionButton.Disabled = false;
        WattSetting.OnTextChanged += _ => SetExtractionButton.Disabled = false;
        SetExtractionButton.OnPressed += _ => OnSetExtractPressed();

        PressureSetting.OnTextChanged += _ => SetPressureButton.Disabled = false;
        SetPressureButton.OnPressed += _ => OnSetPressurePressed();

        EjectButton.OnPressed += _ => EjectPressed?.Invoke();
    }

    public void SetEntity(EntityUid entity, IEntityManager entMan) => this.SetInfoFromEntity(entMan, entity);

    public void UpdateState(FusionReactorControllerBuiState msg)
    {
        AtomList.Update(msg.Plasma.Atoms);
        AtomList.RemoveZero();

        InjectionList.Update(msg.Stored);
        InjectionList.UpdateSelectors(msg.Transfers);

        if (msg.Plasma.TotalMoles > 0)
        {
            ReactorTempValue.Text = Loc.GetString("fusion-reactor-controller-ui-format-temperature", ("value", msg.Plasma.Temperature));
            ReactorPressureValue.Text = Loc.GetString("fusion-reactor-controller-ui-format-pressure", ("value", msg.Plasma.Pressure));
            ReactorExpansionValue.Text = Loc.GetString("fusion-reactor-controller-ui-format-percent", ("value", msg.Plasma.Volume / msg.Plasma.ConstrainedVolume));
            ReactorStabilityValue.Text = Loc.GetString("fusion-reactor-controller-ui-format-percent", ("value", msg.Stability));
        }
        else
        {
            ReactorTempValue.Text = Loc.GetString("fusion-reactor-controller-ui-stat-no-data");
            ReactorPressureValue.Text = Loc.GetString("fusion-reactor-controller-ui-stat-no-data");
            ReactorExpansionValue.Text = Loc.GetString("fusion-reactor-controller-ui-stat-no-data");
            ReactorStabilityValue.Text = Loc.GetString("fusion-reactor-controller-ui-stat-no-data");
        }

        ReactorIntegrityValue.Text = Loc.GetString("fusion-reactor-controller-ui-format-percent", ("value", msg.Integrity));
        ReactorMagTempValue.Text = Loc.GetString("fusion-reactor-controller-ui-format-temperature", ("value", msg.MagnetTemperature));
        ReactorPowerExtractionValue.Text = Loc.GetString("fusion-reactor-controller-ui-format-power", ("power", msg.PowerExtracted));
        ReactorPowerExportValue.Text = Loc.GetString("fusion-reactor-controller-ui-format-power", ("power", msg.PowerExported));

        if (SetExtractionButton.Disabled)
        {
            ExtractionOption.SelectId((int)msg.ExtractMode);
            WattSetting.Text = msg.WattSetting.ToString();
            TemperatureSetting.Text = msg.TempSetting.ToString();
        }

        if (SetPressureButton.Disabled)
        {
            PressureSetting.Text = msg.RequestedMagneticPressure.ToString();
        }

        foreach (var (nid, state) in msg.Batteries)
        {
            if (_batteryEntries.TryGetValue(nid, out var value))
            {
                value.Update(state);
            }
            else
            {
                var entry = new BatteryStateEntry(nid, state);
                _batteryEntries.Add(nid, entry);
                BatteryList.AddChild(entry);
            }
        }

        foreach (var (nid, state) in msg.Masers)
        {
            if (_maserEntries.TryGetValue(nid, out var value))
            {
                value.Update(state);
            }
            else
            {
                var entry = new MaserStateEntry(state);
                entry.SetAMInject += val => OnMaserSetInject?.Invoke(new(nid, new(val)));
                _maserEntries.Add(nid, entry);
                MASERList.AddChild(entry);
            }
        }

        ReactorGraphic.UpdatePlasma(msg.Plasma);
        ReactorGraphic.UpdateMagnets(msg.MagnetTemperature, msg.MagnetCritical);

        WarningStripeTop.Visible = msg.MeltdownStage > FusionReactorMeltdownStage.Stage1;
        WarningStripeBottom.Visible = msg.MeltdownStage > FusionReactorMeltdownStage.Stage1;

        CenterPopup.Visible = msg.MeltdownStage > FusionReactorMeltdownStage.Stage2;
        EjectButton.Visible = msg.CanEject;

        _timeSpan = msg.EventTime;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _accumulator += args.DeltaSeconds;

        var lambda = (MathF.Sin(_accumulator * 4) * 0.5f) + 0.5f;
        var warnColor = Color.InterpolateBetween(Color.FromHex("#FF0000"), Color.FromHex("#FFFF00"), lambda);

        WarningStripeTop.ModulateSelfOverride = warnColor;
        WarningStripeBottom.ModulateSelfOverride = warnColor;
        WarningStripeCenter.ModulateSelfOverride = warnColor.WithAlpha(0.75f);

        var seconds = MathF.Max((float)(_timeSpan - _gameTiming.CurTime).TotalSeconds, 0f);

        CenterCountdown.Text = Loc.GetString("fusion-reactor-controller-ui-format-seconds", ("value", seconds));
        CenterCountdown.ModulateSelfOverride = warnColor;
    }

    #region Messages
    private void OnSetExtractPressed()
    {
        var type = (FusionReactorPowerExtractType)ExtractionOption.SelectedId;
        var wattSetting = float.TryParse(WattSetting.Text, out var watts) && !float.IsNaN(watts) ? watts : -1;
        var tempSetting = float.TryParse(TemperatureSetting.Text, out var temp) && !float.IsNaN(temp) ? temp : -1;

        // Using negative values as an error flag, also acts as a bit of input filtering
        if (watts < 0 || temp < 0)
            return;

        OnExtractSet?.Invoke(new(type, temp, watts));
        SetExtractionButton.Disabled = true;
    }

    private void OnSetPressurePressed()
    {
        if (!float.TryParse(PressureSetting.Text, out var num) || float.IsNaN(num))
            return;

        OnPressureSet?.Invoke(num);
        SetPressureButton.Disabled = true;
    }

    private void UpdateEditInjectButton()
    {
        var protons = EditInjectOption.SelectedId;
        if (!int.TryParse(EditInjectNumber.Text, out var nucleons) || nucleons < protons)
        {
            EditInjectButton.Disabled = true;
            return;
        }

        var neutrons = nucleons - protons;

        EditInjectButton.Text = InjectionList.Contains(new(protons, neutrons))
            ? Loc.GetString("fusion-reactor-controller-ui-remove")
            : Loc.GetString("fusion-reactor-controller-ui-add");
        EditInjectButton.Disabled = false;
    }

    private void OnEditInjectAtom()
    {
        EditInjectButton.Disabled = true;

        if (!int.TryParse(EditInjectNumber.Text, out var nucleons) || nucleons <= 0)
            return;

        var protons = EditInjectOption.SelectedId;
        var neutrons = nucleons - protons;

        if (neutrons < 0)
            return;

        OnEditInject?.Invoke(new(new(protons, neutrons)));
    }

    public List<FusionReactorControllerSetMaserPowerMessage> GetMaserCoalescers()
    {
        List<FusionReactorControllerSetMaserPowerMessage> list = [];

        foreach (var (uid, maser) in _maserEntries)
        {
            if (!maser.CheckIsModified(out var powerLevel))
                continue;

            list.Add(new(uid, new(powerLevel)));
        }
        return list;
    }
    #endregion

    #region Entries
    private sealed class BatteryStateEntry : BoxContainer
    {
        private const int ChargeCells = 5;

        private readonly SpriteView _sprite;
        private readonly BoxContainer _bar;
        private readonly StyleBoxFlat[] _barColors;
        private readonly Label _change;

        public BatteryStateEntry(NetEntity uid, FusionReactorBatteryBuiState state)
        {
            var spriteBox = new BoxContainer()
            {
                SetSize = new(32, 32),
                Margin = new(2),
                Orientation = LayoutOrientation.Vertical,
            };
            _sprite ??= new()
            {
                SetSize = new(32, 32),
                Scale = new(2, 2),
                OverrideDirection = Direction.South,
            };
            _bar ??= new()
            {
                SetWidth = 175,
                HorizontalExpand = false,
                VerticalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                Orientation = LayoutOrientation.Horizontal,
            };
            _change ??= new()
            {
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Right,
                VerticalAlignment = VAlignment.Center,
            };

            Orientation = LayoutOrientation.Horizontal;

            _barColors = new StyleBoxFlat[ChargeCells];

            for (var i = 0; i < ChargeCells; i++)
            {
                var styleBox = new StyleBoxFlat();
                _barColors[i] = styleBox;

                var control = new PanelContainer
                {
                    Margin = new(2, 4),
                    PanelOverride = styleBox,
                    HorizontalExpand = true,
                    VerticalExpand = true,
                };

                _bar.AddChild(control);
            }

            _sprite.SetEntity(uid);

            Update(state);

            spriteBox.AddChild(_sprite);
            AddChild(spriteBox);
            AddChild(_bar);
            AddChild(_change);
        }

        public void Update(FusionReactorBatteryBuiState state)
        {
            var chargeLevel = state.Charge / state.MaxCharge * ChargeCells;

            for (var i = 0; i < ChargeCells; i++)
            {
                var box = _barColors[i];
                var rem = chargeLevel - i;

                box.BackgroundColor = rem >= 1
                    ? Color.FromHex("#22bbff")
                    : rem <= 0 ? Color.FromHex("#202020")
                    : Color.InterpolateBetween(Color.FromHex("#202020"), Color.FromHex("#22bbff"), rem);
            }

            var netRate = state.Input + state.ExternalInput - state.Output;
            _change.Text = Loc.GetString("fusion-reactor-controller-ui-format-power", ("power", Math.Abs(netRate)));
            _change.FontColorOverride = netRate < -0.0001 * state.MaxCharge ? Color.Red : Color.White;
        }
    }

    private sealed class MaserStateEntry : BoxContainer
    {
        private readonly SpriteView _jarView;
        private readonly Label _jarMissing;
        private readonly Label _jarCount;
        private readonly SwitchButton _injecting;
        private readonly SliderIntInput _powerLevel;
        // supresses the OnValueChanged action when it's a BUI state changing the value
        private bool _settingPower;
        private InputCoalescer<int> _powerLevelCoalescer;

        public Action<bool>? SetAMInject;

        public MaserStateEntry(FusionReactorMaserBuiState state)
        {
            var jarBox = new BoxContainer()
            {
                SetSize = new(32, 32),
                Margin = new(2),
                Orientation = LayoutOrientation.Vertical,
            };
            _jarView = new()
            {
                SetSize = new(32, 32),
                Scale = new(2, 2),
                OverrideDirection = Direction.South,
            };
            _jarMissing = new()
            {
                Text = Loc.GetString("fusion-reactor-maser-ui-no-jar"),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                Visible = false,
            };
            _jarCount = new()
            {
                Text = "0",
                HorizontalAlignment = HAlignment.Center,
            };
            _injecting = new()
            {
                Disabled = true,
            };
            _powerLevel = new()
            {
                HorizontalExpand = true,
                VerticalExpand = false,
                VerticalAlignment = VAlignment.Center,
            };

            _injecting.OnPressed += _ => SetAMInject?.Invoke(_injecting.Pressed);
            _powerLevel.OnValueChanged += val =>
            {
                if (!_settingPower)
                    _powerLevelCoalescer.Set(val);
            };

            Orientation = LayoutOrientation.Horizontal;
            MinHeight = 85;

            jarBox.AddChild(_jarMissing);
            jarBox.AddChild(_jarView);
            jarBox.AddChild(_jarCount);

            AddChild(jarBox);
            AddChild(_injecting);
            AddChild(_powerLevel);

            Update(state);
        }

        public void Update(FusionReactorMaserBuiState state)
        {
            _injecting.Pressed = state.AMInjection;

            _settingPower = true;
            _powerLevel.Value = state.PowerSetting;
            _powerLevel.MaxValue = state.MaxPowerSetting;
            _settingPower = false;

            _jarCount.Text = state.Antimatter.ToString();

            var jarPresent = state.AMJar.HasValue;
            _injecting.Disabled = !jarPresent;
            if (jarPresent)
                _jarView.SetEntity(state.AMJar!.Value);
            _jarView.Visible = jarPresent;
            _jarCount.Visible = jarPresent;
            _jarMissing.Visible = !jarPresent;
        }

        public bool CheckIsModified([MaybeNullWhen(false)] out int value) => _powerLevelCoalescer.CheckIsModified(out value);
    }
    #endregion
}