using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Power.Generation.FusionGenerator.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._FarHorizons.Power.UI.FusionReactor;

[GenerateTypedNameReferences]
public sealed partial class FusionReactorGasInletWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    private float _maxTransferRate = 0;

    public event Action<bool>? ToggleStatusButtonPressed;
    public event Action<string>? PowerUseChanged;
    
    public EntityUid? Entity;

    public FusionReactorGasInletWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ToggleStatusButton.OnToggled += _ => ToggleStatusButtonPressed?.Invoke(ToggleStatusButton.Pressed);

        PowerUseInput.OnTextChanged += _ => SetPowerUseButton.Disabled = false;
        SetPowerUseButton.OnPressed += _ =>
        {
            PowerUseChanged?.Invoke(PowerUseInput.Text ??= "");
            SetPowerUseButton.Disabled = true;
        };

        SetMaxPowerUseButton.OnPressed += _ =>
        {
            PowerUseInput.Text = _maxTransferRate.ToString(CultureInfo.CurrentCulture);
            SetPowerUseButton.Disabled = false;
        };

        AtomList.DisplayUnit = "mol/s";
    }

    public void SetEntity(EntityUid? entity) => Entity = entity;

    public void SetTransferRate(float rate)
    {
        PowerUseInput.Text = rate.ToString(CultureInfo.CurrentCulture);
    }

    public void SetMaxTransferRate(float rate)
    {
        _maxTransferRate = rate;
    }

    public void SetPumpStatus(bool enabled)
    {
        ToggleStatusButton.Pressed = enabled;
    }

    public void Update()
    {
        if(!_entManager.TryGetComponent<FusionReactorGasInletComponent>(Entity, out var comp))
            return;

        AtomList.Update(comp.Production);
    }

    protected override void FrameUpdate(FrameEventArgs args) => Update();
}
