
using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FarHorizons.Power.UI.FusionReactor;

/// <summary>
/// Client-side UI used to control a fusion reactor's coolant pump.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FusionReactorCoolantPumpWindow : FancyWindow
{
    public event Action<bool>? ToggleStatusButtonPressed;
    public event Action<string>? PumpTransferRateChanged;

    public FusionReactorCoolantPumpWindow()
    {
        RobustXamlLoader.Load(this);

        ToggleStatusButton.OnToggled += _ => ToggleStatusButtonPressed?.Invoke(ToggleStatusButton.Pressed);

        PumpTransferRateInput.OnTextChanged += _ => SetTransferRateButton.Disabled = false;
        SetTransferRateButton.OnPressed += _ =>
        {
            PumpTransferRateChanged?.Invoke(PumpTransferRateInput.Text ??= "");
            SetTransferRateButton.Disabled = true;
        };

        SetMaxRateButton.OnPressed += _ =>
        {
            PumpTransferRateInput.Text = Atmospherics.MaxTransferRate.ToString(CultureInfo.CurrentCulture);
            SetTransferRateButton.Disabled = false;
        };
    }

    public void SetEntity(EntityUid entity, IEntityManager entMan) => this.SetInfoFromEntity(entMan, entity);

    public void SetTransferRate(float rate) => PumpTransferRateInput.Text = rate.ToString(CultureInfo.CurrentCulture);

    public void SetPumpStatus(bool enabled) => ToggleStatusButton.Pressed = enabled;
}
