using System.Numerics;
using Content.Shared._FarHorizons.Power.Generation.FusionGenerator;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Random;
using Robust.Shared.Timing;

namespace Content.Client._FarHorizons.Power.UI.FusionReactor;

[GenerateTypedNameReferences]
public sealed partial class FusionReactorGraphic : Control
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private readonly IRobustRandom _random = default!;

    private readonly bool _isInit = false;
    private float _frametime = 0;

    private float _magneticPressure = 0;
    private float _magnetTemperature = 0;
    private float _magnetCritical = 0;

    private const string TextureLocation = "/Textures/_FarHorizons/Interface/FusionGenerator/";
    private static readonly string[] _paths = [
        TextureLocation + "reactor_cross_section_left.png",
        TextureLocation + "reactor_cross_section_right.png",
        TextureLocation + "reactor_cross_section_center_a.png",
        TextureLocation + "reactor_cross_section_center_b.png",
        TextureLocation + "reactor_cross_section_center_c.png",
        TextureLocation + "reactor_cross_section_center_d.png",
        TextureLocation + "reactor_magnet_inner.png",
        TextureLocation + "reactor_magnet_outer.png",
    ];

    private static readonly Color _colorBackground = Color.FromHex("#202020");
    private static readonly Color _colorPlasmaMin = Color.FromHex("#22bbff11");
    private static readonly Color _colorPlasmaMax = Color.FromHex("#ffffff");
    private static readonly Color _colorMagnet = Color.FromHex("#22bbff");
    private static readonly Color _colorColumn = Color.FromHex("#4baeff");
    private static readonly Color _colorColumnFail = Color.FromHex("#ff0000");

    private static Color DimColor(Color color)
    {
        var hsv = Color.ToHsv(color);
        hsv.Z /= 4;
        return Color.FromHsv(hsv);
    }

    private readonly Dictionary<string, List<FusionReactorTexture>> _parts = [];

    public FusionReactorGraphic()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        /// This feels like a crime but I found no other way to do it
        _parts["torus_background"] = new()
        {
            new(_resourceCache.GetResource<TextureResource>(_paths[0]))
            {
                VisualColor = _colorBackground
            },
            new(_resourceCache.GetResource<TextureResource>(_paths[1]))
            {
                VisualColor = _colorBackground
            },
        };

        _parts["plasma"] = new()
        {
            new(_resourceCache.GetResource<TextureResource>(_paths[0]))
            {
                ScaleSlew = new(0.72f, 0.5f),
                Phase = _random.NextFloat(MathF.Tau),
            },
            new(_resourceCache.GetResource<TextureResource>(_paths[1]))
            {
                ScaleSlew = new(0.28f, 0.5f),
                Phase = _random.NextFloat(MathF.Tau),
            },
            new(_resourceCache.GetResource<TextureResource>(_paths[0]))
            {
                ScaleSlew = new(0.72f, 0.5f),
                Phase = _random.NextFloat(MathF.Tau),
            },
            new(_resourceCache.GetResource<TextureResource>(_paths[1]))
            {
                ScaleSlew = new(0.28f, 0.5f),
                Phase = _random.NextFloat(MathF.Tau),
            },
            new(_resourceCache.GetResource<TextureResource>(_paths[0]))
            {
                ScaleSlew = new(0.72f, 0.5f),
                Phase = _random.NextFloat(MathF.Tau),
            },
            new(_resourceCache.GetResource<TextureResource>(_paths[1]))
            {
                ScaleSlew = new(0.28f, 0.5f),
                Phase = _random.NextFloat(MathF.Tau),
            },
        };

        _parts["center_column"] = new()
        {
            new(_resourceCache.GetResource<TextureResource>(_paths[2]))
            {
                Phase = 0
            },
            new(_resourceCache.GetResource<TextureResource>(_paths[3]))
            {
                Phase = 3 * MathF.PI / 2
            },
            new(_resourceCache.GetResource<TextureResource>(_paths[4]))
            {
                Phase = MathF.PI
            },
            new(_resourceCache.GetResource<TextureResource>(_paths[5]))
            {
                Phase = MathF.PI / 2
            },
        };

        _parts["magnetic_lines"] = new()
        {
            new(_resourceCache.GetResource<TextureResource>(_paths[6])),
            new(_resourceCache.GetResource<TextureResource>(_paths[7]))
            {
                Phase = MathF.PI / 2
            },
        };
        _isInit = true;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);
        if (!_isInit)
            return;

        foreach (var (name, part) in _parts)
        {
            foreach (var texture in part)
            {
                var xhalf = Width * UIScale;
                var yhalf = Height * UIScale;
                var xscale = 1 - texture.ScaleSlew.X;
                var yscale = 1 - texture.ScaleSlew.Y;
                var xfactor = xhalf * xscale;
                var yfactor = yhalf * yscale;
                handle.DrawTextureRect(texture.Sprite, UIBox2.FromDimensions(
                    xfactor - (xfactor * texture.Scale) + (texture.Offset.X * Width * UIScale * texture.Scale),
                    yfactor - (yfactor * texture.Scale) + (texture.Offset.Y * Width * UIScale * texture.Scale),
                    Width * UIScale * texture.Scale,
                    Height * UIScale * texture.Scale
                    ), texture.VisualColor);

            }
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_isInit)
            return;

        _frametime += args.DeltaSeconds;

        foreach (var texture in _parts["plasma"])
        {
            texture.Offset.Y = MathF.Sin((_frametime * 1f) + texture.Phase) * 0.01f;
            texture.Offset.X = MathF.Cos((_frametime * 1f) + texture.Phase) * 0.01f;
        }

        foreach (var texture in _parts["magnetic_lines"])
        {
            var mag = 1e5f / _magneticPressure;
            var pulse = Color.InterpolateBetween(_colorMagnet, DimColor(_colorMagnet), (MathF.Sin((_frametime / MathF.Max(2 * mag, 0.1f)) + texture.Phase) / 2) + 0.5f);
            texture.VisualColor = Color.InterpolateBetween(_colorBackground, pulse, MathF.Min(_magneticPressure * 1e-5f, 1));
        }

        foreach (var texture in _parts["center_column"])
        {
            if (_magnetTemperature > _magnetCritical)
            {
                texture.VisualColor = _colorBackground;
                continue;
            }
            // Magic number that makes it so that the red color only comes up if it's within 10 k of TC
            var magic = 20;
            var diff = _magnetTemperature - _magnetCritical + magic;

            var interp = diff > 0 ? Math.Clamp((magic / diff) - 1, 0, 1) : 1;
            var baseColor = Color.InterpolateBetween(_colorColumnFail, _colorColumn, interp);
            var pulse = Color.InterpolateBetween(baseColor, DimColor(baseColor), (MathF.Sin(_frametime + texture.Phase) / 2) + 0.5f);
            texture.VisualColor = pulse;
        }
    }

    public void UpdatePlasma(FusionMixEntry fusionMix)
    {
        if (!_isInit)
            return;

        var scale = fusionMix.TotalMoles > 0 ? fusionMix.Volume / fusionMix.ConstrainedVolume : 0;
        var list = _parts["plasma"];
        list[0].Scale = scale;
        list[0].VisualColor = PlasmaColor(0.8f * fusionMix.Temperature / 1e11f);
        list[1].Scale = scale;
        list[1].VisualColor = PlasmaColor(0.8f * fusionMix.Temperature / 1e11f);

        list[2].Scale = scale * 0.8f;
        list[2].VisualColor = PlasmaColor(0.9f * fusionMix.Temperature / 1e9f);
        list[3].Scale = scale * 0.8f;
        list[3].VisualColor = PlasmaColor(0.9f * fusionMix.Temperature / 1e9f);

        list[4].Scale = scale * 0.6f;
        list[4].VisualColor = PlasmaColor(fusionMix.Temperature / 1e7f);
        list[5].Scale = scale * 0.6f;
        list[5].VisualColor = PlasmaColor(fusionMix.Temperature / 1e7f);

        _magneticPressure = fusionMix.Pressure;

        static Color PlasmaColor(float ratio) => Color.InterpolateBetween(_colorPlasmaMin, _colorPlasmaMax, Math.Min(ratio, 1));
    }

    public void UpdateMagnets(float temperature, float criticalTemp)
    {
        _magnetTemperature = temperature;
        _magnetCritical = criticalTemp;
    }

    private sealed class FusionReactorTexture(Texture sprite)
    {
        public Color VisualColor = Color.FromHex("#ff00ff");
        public Texture Sprite = sprite;

        public float Scale { get; set => field = Math.Clamp(value, 0f, 1f); } = 1;
        public Vector2 ScaleSlew = Vector2.Zero;
        public Vector2 Offset = Vector2.Zero;
        public float Phase = 0;
    }
}

