using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Power.Generation.FusionGenerator;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._FarHorizons.Power.UI.FusionReactor;

[GenerateTypedNameReferences]
public sealed partial class FusionReactorBatteryWindow : FancyWindow
{
    /// Collection of consts from the <see cref="BatteryMenu"/>
    private const float MaxEtaValueMinutes = 60;
    private const float NotApplicableEtaHighCutoffMinutes = 1000;
    private const float NotApplicableEtaLowCutoffMinutes = 0.01f;
    private const float PrecisionRoundFactor = 100_000;

    private const int ChargeCells = 12;

    private bool _suppressInputSlider = false;
    private readonly StyleBoxFlat[] _chargeMeter;
    private float _chargeLevel;

    public Action<float>? SetChargeRate;
    public Action<bool>? SetCanCharge;
    public Action<bool>? SetCanDischarge;

    public FusionReactorBatteryWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MaxExternalInputSlider.OnValueChanged += _ =>
        {
            if (!_suppressInputSlider)
                SetChargeRate?.Invoke(MaxExternalInputSlider.Value);
        };

        InputBreaker.OnPressed += _ => SetCanCharge?.Invoke(InputBreaker.Pressed);
        OutputBreaker.OnPressed += _ => SetCanDischarge?.Invoke(OutputBreaker.Pressed);

        _chargeMeter = new StyleBoxFlat[ChargeCells];

        for (var i = ChargeCells - 1; i >= 0; i--)
        {
            var styleBox = new StyleBoxFlat();
            _chargeMeter[i] = styleBox;

            var control = new PanelContainer
            {
                Margin = new Thickness(2),
                PanelOverride = styleBox,
                HorizontalExpand = true,
                VerticalExpand = true,
            };

            ChargeMeter.AddChild(control);
        }
    }

    public void Update(FusionReactorBatteryBuiState msg)
    {
        ExternalInputValue.Text = Loc.GetString("fusion-reactor-battery-ui-power-format", ("power", msg.ExternalInput));

        _suppressInputSlider = true;
        MaxExternalInputSlider.Value = msg.MaxExternalInput;
        MaxExternalInputSlider.MinValue = msg.MinMaxExternalInput;
        MaxExternalInputSlider.MaxValue = msg.MaxMaxExternalInput;
        _suppressInputSlider = false;

        MaxExternalInputValue.Text = Loc.GetString("fusion-reactor-battery-ui-power-format", ("power", msg.MaxExternalInput));

        InternalInputValue.Text = Loc.GetString("fusion-reactor-battery-ui-power-format", ("power", msg.Input));

        InputBreaker.Pressed = msg.CanCharge;

        var chargeLevel = msg.Charge / msg.MaxCharge;
        ChargeLevelValue.Text = Loc.GetString("fusion-reactor-battery-ui-charge-percent", ("charge", chargeLevel));
        ChargeValue.Text = FormatJoules(msg.Charge);
        _chargeLevel = chargeLevel * ChargeCells;

        OutputBreaker.Pressed = msg.CanDischarge;
        OutputValue.Text = Loc.GetString("fusion-reactor-battery-ui-power-format", ("power", msg.Output));

        /// Logic from the <see cref="BatteryMenu"/>
        var netRate = msg.ExternalInput + msg.Input - msg.Output;
        if (Math.Abs(netRate) < msg.MaxCharge / PrecisionRoundFactor)
            netRate = 0;

        var storageEtaDiff = netRate > 0 ? (msg.MaxCharge - msg.Charge) * (1 / msg.Efficiency) : -msg.Charge;
        var etaTimeSeconds = storageEtaDiff / netRate;
        var etaTimeMinutes = etaTimeSeconds / 60.0;

        ChargeETAText.Text = Loc.GetString(
            netRate > 0 ? "fusion-reactor-battery-ui-eta-full" : "fusion-reactor-battery-ui-eta-empty");

        if (!double.IsFinite(etaTimeMinutes)
            || Math.Abs(etaTimeMinutes) > NotApplicableEtaHighCutoffMinutes
            || Math.Abs(etaTimeMinutes) < NotApplicableEtaLowCutoffMinutes)
        {
            ChargeETA.Text = Loc.GetString("fusion-reactor-battery-ui-eta-value-na");
        }
        else
        {
            ChargeETA.Text = Loc.GetString(
                etaTimeMinutes > MaxEtaValueMinutes ? "fusion-reactor-battery-ui-eta-value-max" : "fusion-reactor-battery-ui-eta-value",
                ("minutes", Math.Min(Math.Ceiling(etaTimeMinutes), MaxEtaValueMinutes)));
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        for (var i = 0; i < ChargeCells; i++)
        {
            var box = _chargeMeter[i];
            var rem = _chargeLevel - i;

            box.BackgroundColor = rem >= 1
                ? Color.FromHex("#22bbff")
                : rem <= 0 ? Color.FromHex("#202020")
                : Color.InterpolateBetween(Color.FromHex("#202020"), Color.FromHex("#22bbff"), rem);
        }
    }

    public void SetEntity(EntityUid entity, IEntityManager entMan)
    {
        EntityView.SetEntity(entity);

        this.SetInfoFromEntity(entMan, entity);
    }

    private static string FormatJoules(float input)
    {
        var maxPlaces = 5;
        var places = 0;
        while (input > 1000 && places < maxPlaces)
        {
            input /= 1000;
            places++;
        }

        return Loc.GetString("fusion-reactor-battery-fmt-joules", ("divided", input), ("places", places));
    }
}