using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Power.Generation.FusionGenerator;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FarHorizons.Power.UI.FusionReactor;

[GenerateTypedNameReferences]
public sealed partial class FusionReactorMaserWindow : FancyWindow
{
    public Action<int>? SetPowerLevel;
    public Action<bool>? SetAMInject;

    public FusionReactorMaserWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ToggleInjectButton.OnPressed += _ => SetAMInject?.Invoke(ToggleInjectButton.Pressed);
        MaserPowerLevelSlider.OnValueChanged += _ => SetPowerLevel?.Invoke((int)MaserPowerLevelSlider.Value);
    }

    public void SetEntity(EntityUid maser)
    {
    }

    public void Update(FusionReactorMaserBuiState msg)
    {
        ToggleInjectButton.Pressed = msg.AMInjection;

        MaserPowerLevelSlider.Value = msg.PowerSetting;
        MaserPowerLevelSlider.MaxValue = msg.MaxPowerSetting;

        if (msg.AMJar.HasValue)
            EntityView.SetEntity(msg.AMJar.Value);
    }
}