using Content.Shared._FarHorizons.Power.Generation.FusionGenerator;
using Content.Shared._FarHorizons.Power.Generation.FusionGenerator.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FarHorizons.Power.UI.FusionReactor;

[GenerateTypedNameReferences]
public sealed partial class FusionReactorInvalidPopup : BoxContainer
{
    private bool _dismissed = false;
    private bool _displayingCustom = false;
    // private FusionReactorValidity _lastState = FusionReactorValidity.Valid;
    public bool Valid { get; private set; } = true;

    public FusionReactorInvalidPopup()
    {
        RobustXamlLoader.Load(this);
        ACKButton.OnPressed += _ => OnDismiss();
    }

    public void Update(FusionReactorValidityBuiMessage msg)
    {
        if (_displayingCustom)
            return;

        var prevValid = Valid;
        Valid = msg.Validity == FusionReactorValidity.Valid;

        if (prevValid && !Valid)
            _dismissed = false;

        Visible = !_dismissed && !Valid;

        InvalidLabel.Visible = true;
        InvalidTori.Visible = msg.Validity.HasFlag(FusionReactorValidity.InsufficientTorus);
        InvalidMagnet.Visible = msg.Validity.HasFlag(FusionReactorValidity.InsufficientMagnet);
        InvalidAlone.Visible = msg.Validity.HasFlag(FusionReactorValidity.Alone);
        CustomText.Visible = false;
    }

    public void Display(string text)
    {
        CustomText.Text = _displayingCustom ? $"{CustomText.Text}\n{text}" : text;

        _dismissed = false;
        _displayingCustom = true;
        Visible = true;

        InvalidLabel.Visible = false;
        InvalidTori.Visible = false;
        InvalidMagnet.Visible = false;
        InvalidAlone.Visible = false;
        CustomText.Visible = true;
    }

    public void Show()
    {
        _dismissed = false;
        Visible = true;
    }

    private void OnDismiss()
    {
        _dismissed = !_displayingCustom;
        _displayingCustom = false;
        Visible = false;
    }
}