- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleScientist #FH
  name: Scientist Abductor Role #FH
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: ScientistAbductorAntag #FH
  - type: Abductor

#FarHorizons Start
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAgentAbductor
  name: Agent Abductor Role
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: AgentAbductorAntag
  - type: Abductor
#FarHorizons End

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBrighteye
  name: Brighteye Role
  components:
  - type: MindRole
    antagPrototype: Brighteye
    subtype: roles-antag-brighteye-name
    exclusiveAntag: true
  - type: BrighteyeRole