- type: entity
  parent: OrganBase
  id: OrganBaseTail
  name: tail
  abstract: true
  components:
  - type: Organ
    category: Tail
  - type: Sprite
    state: tail
  - type: VisualOrgan
    layer: enum.HumanoidVisualLayers.Tail
    data:
      state: tail
  - type: VisualOrganMarkings
    markingData:
      layers:
      - Tail
      - TailCover 

- type: entity
  id: BaseAnimalNubody
  parent:
  - InventoryBase
  - BaseSpeciesLayers
  abstract: true
  components:
  - type: Body
  - type: VisualBody
  - type: ComplexInteraction
  - type: Hands
  - type: ContainerContainer
    body_organs: !type:Container
      showEnts: False
      occludes: True
      ents: []
    shoes: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    jumpsuit: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    outerClothing: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    gloves: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    neck: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    pin: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    mask: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    eyes: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    ears: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    head: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    pocket1: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    pocket2: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    suitstorage: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    suitstorage2: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    id: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    belt: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    rig: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
    back: !type:ContainerSlot
      showEnts: False
      occludes: False
      ent: null
  - type: Appearance
  - type: MovementOrganExpectedToMove # Far Horizons
  - type: UserInterface
    interfaces:
      enum.SurgeryUIKey.Key:
        type: SurgeryBui
      enum.StrippingUiKey.Key:
        type: StrippableBoundUserInterface
  - type: Blindable
  - type: DarkenedVision
  - type: VisionOrganRequiredForVision
  - type: GenericVisualizer
    visuals:
      enum.CreamPiedVisuals.Creamed:
        clownedon:
          True: { visible: true }
          False: { visible: false }